#!/usr/bin/env python3
"""Run the Vault server.

    python run.py --init     write a .env with fresh keys (do this once)
    python run.py            start the development server on :5000

For production, put this behind TLS and a real WSGI server, e.g.
    gunicorn -w 4 "run:app"
"""

from __future__ import annotations

import base64
import os
import secrets
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
ENV_PATH = BASE_DIR / ".env"


def init() -> int:
    if ENV_PATH.exists():
        print(f".env already exists at {ENV_PATH} — leaving it alone.")
        print("Delete it first if you really want new keys. Rotating MASTER_KEY")
        print("makes every file already in storage unreadable.")
        return 1

    env = (
        "# Generated by run.py --init. Keep this file out of version control.\n"
        f"SECRET_KEY={secrets.token_hex(32)}\n"
        f"MASTER_KEY={base64.urlsafe_b64encode(os.urandom(32)).decode()}\n"
        "STORAGE_DIR=storage\n"
        "DATABASE_PATH=storage/vault.db\n"
        "MAX_UPLOAD_MB=200\n"
        "DEFAULT_LINK_TTL_HOURS=24\n"
        "COOKIE_SECURE=0\n"
    )
    ENV_PATH.write_text(env)
    os.chmod(ENV_PATH, 0o600)
    print(f"Wrote {ENV_PATH}")
    print("Back up MASTER_KEY somewhere safe. Without it, stored files cannot be decrypted.")
    print("Now run: python run.py")
    return 0


if __name__ == "__main__" and "--init" in sys.argv:
    raise SystemExit(init())

from app import create_app  # noqa: E402

app = create_app()

if __name__ == "__main__":
    if not os.environ.get("MASTER_KEY"):
        print("No MASTER_KEY found. Run: python run.py --init")
        raise SystemExit(1)
    app.run(host="127.0.0.1", port=int(os.environ.get("PORT", 5000)), debug=False)
